# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stupid-spin-tracker',
                'doc_host': 'https://aetb.github.io',
                'git_url': 'https://github.com/aetb/stupid-spin-tracker',
                'lib_path': 'stupid_spin_tracker'},
  'syms': {'stupid_spin_tracker.core': {'stupid_spin_tracker.core.foo': ('core.html#foo', 'stupid_spin_tracker/core.py')}}}
